### ISSUE TITLE
Update Checker Message Error on Join

### ISSUE THREAD

**Issue by slooshied** [zDevelopers/ImageOnMap#164]
`[15:32:25 ERROR]: [ImageOnMap] Exception :
java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R3.IChatBaseComponent, net.minecraft.server.v1_16_R3.ChatMessageType)
        at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2151) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendChatPacket(MessageSender.java:524) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendMessage(MessageSender.java:169) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendSystemMessage(MessageSender.java:390) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.UpdateChecker.lambda$getDefaultPlayerNotificationSender$3(UpdateChecker.java:229) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.UpdateChecker.lambda$onPlayerJoin$4(UpdateChecker.java:248) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-585]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-585]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-585]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-585]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-585]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-585]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
        
      
![image](https://user-images.githubusercontent.com/70556905/114320376-50db5980-9adb-11eb-869c-7021b4a552d2.png)

**Comment by Vlammar** [comment]
Already aware of this issue, thanks for posting logs :). The PR #163 will fix this
