### ISSUE TITLE
I get the error "The player <PlayerName> does not exist." when me and players do /maps while im on my server. 

### ISSUE THREAD

**Issue by CobaltBlue07** [zDevelopers/ImageOnMap#179]
The console message is:

04.05 22:18:16 [Server] INFO CobaltBlue07 issued server command: /maps
04.05 22:18:17 [Server] WARN [ImageOnMap] Error while getting player UUID 

![opera_UihD5y0dbf](https://user-images.githubusercontent.com/83672438/117064725-3d648c80-ad2f-11eb-8b48-1048f6934365.png)

And when I do "/maptool list" the console message is:

04.05 22:20:52 [Server] INFO CobaltBlue07 issued server command: /maptool list
04.05 22:20:52 [Server] WARN [ImageOnMap] Error while getting player UUID
04.05 22:20:52 [Server] WARN [ImageOnMap] Task #503 for ImageOnMap v4.1.2 generated an exception
04.05 22:20:52 [Server] INFO java.lang.NullPointerException: null
04.05 22:20:52 [Server] INFO at fr.moribus.imageonmap.map.MapManager.getExistingPlayerMapStore(MapManager.java:368) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.moribus.imageonmap.map.MapManager.getPlayerMapStore(MapManager.java:354) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.moribus.imageonmap.map.MapManager.getMapList(MapManager.java:169) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.moribus.imageonmap.commands.maptool.ListCommand.lambda$run$0(ListCommand.java:83) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.commands.CommandWorkers$1.errored(CommandWorkers.java:29) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.worker.WorkerCallbackManager$WorkerRunnableInfo.runCallback(WorkerCallbackManager.java:124) ~[?:?]
04.05 22:20:52 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.worker.WorkerCallbackManager.run(WorkerCallbackManager.java:105) ~[?:?]
04.05 22:20:52 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-570]
04.05 22:20:52 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

![opera_4Vu0kLuRQQ](https://user-images.githubusercontent.com/83672438/117065054-a3511400-ad2f-11eb-93c8-d70cc08c1437.png)

**Comment by CobaltBlue07** [comment]
Also, this might have happened after a member tried making a map with a discord image link

**Comment by koshernerd** [comment]
This same thing has happened to my server as well. anytime I place a map that I already have, it disappears. when trying to run any of the console commands, everyone gets the same printout from the console.

the only way I was able to make anything function, was only able to move a preexisting map, and I would have to get into creative in order to make it work.

I'd have to, be in survival, pickup the map I want to move, go into creative, and then place the map. I am unable to open:

/maptool explorer  

and unable to make a new map.

I've only noticed this yesterday (5/4/21) I moved my server to a new desktop I've built specifically for my server, last week. the last time I have used the maptool was the beginning of March.

**Comment by CobaltBlue07** [comment]
My /maps command works today, I removed the last added map from the maps file and restarted the server couple of times but im pretty sure the discord link was crashing the plugin also make sure the plugin is up to date. Hope this issue gets fixed with the update.

**Comment by koshernerd** [comment]
> My /maps command works today, I removed the last added map from the maps file and restarted the server couple of times but im pretty sure the discord link was crashing the plugin also make sure the plugin is up to date. Hope this issue gets fixed with the update.

I will try this tonight and report back. my last map I made was quite large as well.

**Comment by koshernerd** [comment]
okay, UPDATE. after reinstalling ImageOnMap .jar file with the most up to date file.... which I already did do. and rather then reloading my server, I stopped it, rebooted the computer, and started the server again. everything works PERFECTLY!!
