### ISSUE TITLE
Gif

### ISSUE THREAD

**Issue by Neverlookbackgrg** [zDevelopers/ImageOnMap#20]
I tried creating an animated Gif but i am not sure if support as a moving pickture or just a gif pic

**Comment by prokopyl** [comment]
GIFs (and animated maps in general) are not yet supported. They will someday, but it isn't a priority for now, as it is unusable in most cases, because of the high resources it demands, which is often way too much for most servers.

**Comment by Neverlookbackgrg** [comment]
what is that error for?
[Server thread/WARN]: [ImageOnMap] Task #8857 for ImageOnMap v2.7 generated an exception
java.lang.NullPointerException
	at fr.moribus.ImageOnMap.TacheTraitementMap.run(TacheTraitementMap.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-880a532]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_76]

**Comment by AmauryCarrade** [comment]
ImageOnMap 2.7 is no longer supported, as we work on the new 3.0 version (currently 2.99), a complete rewrite with nearly all bugs fixed and a lot of new features.

Thanks anyway!
