### ISSUE TITLE
[ImageOnMap] Unable to get Splatter Map attribute on item

### ISSUE THREAD

**Issue by muhyomuhyo** [zDevelopers/ImageOnMap#200]
I can't put a single map into a frame in survival mode even with proper permission.
The map disappeared immediately after show it very short time (less than 100ms)  with console error.
*in creative mode, nothing happened , works fine.
*it happened after updating ImageOnMap from 4.0 to 4.1.2.

paper 1.16.5 (java11) & spigot 1.17(java16)

to reproduce
- make a single map (1 x1 size)
- get the map with map ID (   ex. minecraft:give player_name minecraft:filled_map{map:4720}   )
- survival mode
- put a map into a item frame.

```
[18:40:53] [Server thread/ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to find class: ItemStack
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.getMinecraftClass(NBT.java:248) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.init(NBT.java:265) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:72) ~[?:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:155) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:255) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:349) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor558.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2102) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2144) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(SourceFile:116) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2094) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.ItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getMinecraftClassByName(Reflection.java:106) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.getMinecraftClass(NBT.java:246) ~[?:?]
        ... 31 more
[18:40:55] [Server thread/INFO]: yukkuripannda issued server command: /menu
[18:40:55] [Server thread/ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to find class: ItemStack
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.getMinecraftClass(NBT.java:248) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.init(NBT.java:265) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:72) ~[?:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:155) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:255) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:349) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor558.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2102) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2144) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(SourceFile:116) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2094) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.ItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[paperclip.jar:3161-Spigot-f773da8-f81f499]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getMinecraftClassByName(Reflection.java:106) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.getMinecraftClass(NBT.java:246) ~[?:?]
        ... 31 more
```

**Comment by AmauryCarrade** [comment]
This is a 1.17-compatibilty issue. Closing on behalf of the unique issue for this: #198. Thanks for the stack trace, we're working on this but there are lots of work.
