### ISSUE TITLE
EntityPickupItemEvent event not found for 1.8 servers

### ISSUE THREAD

**Issue by Elikill58** [zDevelopers/ImageOnMap#246]
This is the full error with v4.2.1 :
```
[Server thread/ERROR]: [ImageOnMap] Plugin ImageOnMap v4.2.1 has failed to register events for class fr.moribus.imageonmap.image.MapInitEvent because org/bukkit/event/entity/EntityPickupItemEvent does not exist.
[Server thread/ERROR]: Error occurred while enabling ImageOnMap v4.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityPickupItemEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_312]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_312]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_312]
	at fr.zcraft.imageonmap.quartzlib.components.events.FutureEvents.registerFutureEvents(FutureEvents.java:78) ~[?:?]
	at fr.zcraft.imageonmap.quartzlib.core.QuartzLib.registerEvents(QuartzLib.java:180) ~[?:?]
	at fr.moribus.imageonmap.image.MapInitEvent.init(MapInitEvent.java:73) ~[?:?]
	at fr.moribus.imageonmap.ImageOnMap.onEnable(ImageOnMap.java:123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.EntityPickupItemEvent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	... 18 more
```

**Comment by AmauryCarrade** [comment]
This version is only compatible with 1.17+, as stated in the [release notes](https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1), sorry. You'll have to use an old version for 1.8 (ImageOnMap 3.1 should do).
