### ISSUE TITLE
Multiply map does not render

### ISSUE THREAD

**Issue by n08i40k** [zDevelopers/ImageOnMap#247]
Server: Linux x64. Airplane version git-Airplane-112 (MC: 1.17.1)
When you right-click on a frame with a map consisting of several fragments, an error appears and the picture does not appear. 
```
[06:54:51 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to retrieve NBT data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:77) ~[ImageOnMap-4.2.1.jar:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:145) ~[ImageOnMap-4.2.1.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:263) ~[ImageOnMap-4.2.1.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:343) ~[ImageOnMap-4.2.1.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.17.1.jar:git-Airplane-112]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2427) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onInteraction(ServerGamePacketListenerImpl.java:2477) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2419) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-112]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: fr.zcraft.imageonmap.quartzlib.components.nbt.NBTException: Unable to retrieve NBT tag data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:288) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.1.jar:?]
        ... 28 more
Caused by: java.lang.NoSuchFieldException: map
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getField(Reflection.java:170) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:137) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:157) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:286) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.1.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.1.jar:?]
        ... 28 more
```

**Comment by n08i40k** [comment]
Recompile with updated QuartzLib fix this error
