### ISSUE TITLE
1.19 Unable to get Splatter Map attribute on item

### ISSUE THREAD

**Issue by ProGoofster** [zDevelopers/ImageOnMap#269]
[17:52:05 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to retrieve NBT data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:77) ~[ImageOnMap-4.2.3.jar:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:147) ~[ImageOnMap-4.2.3.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:263) ~[ImageOnMap-4.2.3.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:343) ~[ImageOnMap-4.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2660) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2710) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2652) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: fr.zcraft.imageonmap.quartzlib.components.nbt.NBTException: Unable to retrieve NBT tag data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:288) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.3.jar:?]
        ... 28 more
Caused by: java.lang.NoSuchFieldException: map
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getField(Reflection.java:170) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:137) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:157) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:286) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.3.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.3.jar:?]
        ... 28 more

**Comment by ColdeZhang** [comment]
Same problem

[17:52:05 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item

**Comment by Lacosst0** [comment]
Same

**Comment by Froxcey** [comment]
OP didn't provide enough information, so here post mine:
This error message is generated whenever a new image is made through /tomap or an image is placed on an item frame. The item frame doesn't have the full image on but the bottom left corner one.
JRE: v18.0.2.1+1-1
Paper: version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
Plugins: ImageOnMap (built from source, master branch commit ebdad81)

This issue is likely caused by outdated quartzlib (the NBT tag library), so someone will need to update this unmaintained plugin and the dependency.

Also, please avoid adding comments like "same" as it doesn't contribute to anything. Instead, please react with the eye emoji and post something informative like potential fixes.

![vibe](https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif)
