### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by MossCG** [zDevelopers/ImageOnMap#273]
pls support 1.19.2
I use this plugin on my 1.19.2 server
when I place a image map, an exception was thrown:
[17:07:20 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to retrieve NBT data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:77) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:145) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:263) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:343) ~[ImageOnMap-4.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1758]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.performInteraction(ServerGamePacketListenerImpl.java:3011) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3063) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:3003) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1435) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1758]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: fr.zcraft.imageonmap.quartzlib.components.nbt.NBTException: Unable to retrieve NBT tag data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:288) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 28 more
Caused by: java.lang.NoSuchFieldException: map
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getField(Reflection.java:170) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:137) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:157) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:286) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 28 more

**Comment by evanonym0us** [comment]
This is a big problem, please add support.

**Comment by AskSkivdal** [comment]
You can place it manualy with /maps and right clicking the map.

**Comment by cyatarow** [comment]
To be honest, the official release of Minecraft 1.20 is not that far away, so please be ready not only for 1.19.x, but also for 1.20.

**Comment by lynrayy** [comment]
This plugin is same but working
https://www.spigotmc.org/resources/imageonmapretired.103293/
