### ISSUE TITLE
Unocode UTF-8

### ISSUE THREAD

**Issue by lynrayy** [zDevelopers/ImageOnMap#277]
Please compile your plugin in UTF8 
![image](https://user-images.githubusercontent.com/59417884/205187128-92c1299d-4f8e-4f60-a7e8-1d3c7cf7ea99.png)
![image](https://user-images.githubusercontent.com/59417884/205187142-b5009e90-f009-4b9a-8f6b-f2ecb11cb011.png)

**Comment by lynrayy** [comment]
It also just not working with imgur sometimes. It gave me 1 piece of 1x2 map and send error and chat

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/205187406-87e358b9-1638-40c1-8470-ea076a95559c.png)
It gives me half of mapart. 
Even if it is done in some other way, the plugin is not intuitive and this is bad - people without a guide will not be able to understand how it works

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/205187959-f6d523fa-1f73-4446-8b0d-fa39d9ddf7f3.png)

**Comment by lynrayy** [comment]
Hm
`[03:33:05 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to retrieve NBT data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:77) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:145) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:263) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:343) ~[ImageOnMap-4.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-290]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2914) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2970) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2906) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-290]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: fr.zcraft.imageonmap.quartzlib.components.nbt.NBTException: Unable to retrieve NBT tag data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:288) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 28 more
Caused by: java.lang.NoSuchFieldException: map
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getField(Reflection.java:170) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:137) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:157) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:286) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 28 more`

**Comment by lynrayy** [comment]
It is 1.19.2

**Comment by TheStepashich** [comment]
Hi, I have a similar problem with the plugin. Now I will try to fix it by my own efforts, and most importantly to understand the cause!
