### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by GeoGb1** [zDevelopers/ImageOnMap#287]
```
[17:54:35 ERROR]: [ImageOnMap] Unable to get Splatter Map attribute on item
fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSException: Unable to retrieve NBT data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:77) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.hasSplatterAttributes(SplatterMapManager.java:145) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:263) ~[ImageOnMap-4.2.2.jar:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:343) ~[ImageOnMap-4.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-98]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-98]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2817) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2865) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2806) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-98]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: fr.zcraft.imageonmap.quartzlib.components.nbt.NBTException: Unable to retrieve NBT tag data
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:288) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 30 more
Caused by: java.lang.NoSuchFieldException: map
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getField(Reflection.java:170) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:137) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.tools.reflection.Reflection.getFieldValue(Reflection.java:157) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTType.getData(NBTType.java:286) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBTCompound.<init>(NBTCompound.java:72) ~[ImageOnMap-4.2.2.jar:?]
        at fr.zcraft.imageonmap.quartzlib.components.nbt.NBT.fromItemStack(NBT.java:75) ~[ImageOnMap-4.2.2.jar:?]
        ... 30 more
```

**Comment by Komas19-new** [comment]
the plugin is outdated, you can try this plugin instead: https://www.spigotmc.org/resources/imageframe-load-images-on-maps-item-frames-support-gifs-map-markers-survival-friendly.106031/

**Comment by GeoGb1** [comment]
> the plugin is outdated, you can try this plugin instead: https://www.spigotmc.org/resources/imageframe-load-images-on-maps-item-frames-support-gifs-map-markers-survival-friendly.106031/

yeah, i already did that

**Comment by moemeow233** [comment]
> the plugin is outdated, you can try this plugin instead: https://www.spigotmc.org/resources/imageframe-load-images-on-maps-item-frames-support-gifs-map-markers-survival-friendly.106031/

Hi, Is this plugin compatible with ImageOnMap's data?
