### ISSUE TITLE
maptool explore Command bug

### ISSUE THREAD

**Issue by Eiki1** [zDevelopers/ImageOnMap#29]
The `/maptool explore` Command does not work.

```
[03:00:24] [Server thread/INFO]: Eiki issued server command: /maptool explore
[03:00:24] [Server thread/WARN]: [ImageOnMap] Task #27 for ImageOnMap v2.99 generated an exception
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_91]
	at fr.moribus.imageonmap.components.i18n.I18n.getClosestTranslator(I18n.java:321) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.I18n.translate(I18n.java:553) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.I.t(I.java:165) ~[?:?]
	at fr.moribus.imageonmap.gui.MapListGui.onUpdate(MapListGui.java:118) ~[?:?]
	at fr.moribus.imageonmap.components.gui.GuiBase.update(GuiBase.java:79) ~[?:?]
	at fr.moribus.imageonmap.components.gui.InventoryGui.update(InventoryGui.java:81) ~[?:?]
	at fr.moribus.imageonmap.components.gui.ActionGui.update(ActionGui.java:282) ~[?:?]
	at fr.moribus.imageonmap.components.gui.GuiBase.open(GuiBase.java:139) ~[?:?]
	at fr.moribus.imageonmap.components.gui.InventoryGui.open(InventoryGui.java:117) ~[?:?]
	at fr.moribus.imageonmap.components.gui.Gui$1.run(Gui.java:112) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:802) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-792]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```
http://pastebin.com/6qeXPvYr

**Comment by AmauryCarrade** [comment]
Probably related to a730aab1f1ee63cf782d59cc78f82cf05b15f0ce, cc @prokopyl. Seems to be a zLib related bug.

What's the primary language of your Minecraft client?

**Comment by Eiki1** [comment]
English (US)

**Comment by prokopyl** [comment]
I can't reproduce this issue, what Bukkit/Spigot version are you using ? 

Also, in the latest ImageOnMap build, it should print additional information and fallback gracefully instead of throwing an NPE now. Can you give the console output with the latest build ?

**Comment by Eiki1** [comment]
This ist my server log

http://pastebin.com/EZ8Yb10y

The config from ImageOnMap ist the default config

**Comment by prokopyl** [comment]
Okay, I can reproduce it now (I set the plugin's language as de-DE, which does not exist in ImageOnMap yet). The latest build should fix the issue.

**Comment by Eiki1** [comment]
Perfekt on my test server it works. I try it later on my live server.

**Comment by Eiki1** [comment]
Its working Perfekt :)
