### ISSUE TITLE
X11 error (server crash)

### ISSUE THREAD

**Issue by Boy132** [zDevelopers/ImageOnMap#52]
My server crashed with this error. (I just joined and it crashed) It's a Linux server, I don't know if thats a problem?

**Crashreport:**
[crashreport.txt](https://github.com/zDevelopers/ImageOnMap/files/2151088/crashreport.txt)

**Error in Console:**
java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:1.8.0_171]
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65) ~[?:1.8.0_171]
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115) ~[?:1.8.0_171]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74) ~[?:1.8.0_171]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_171]
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_171]
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_171]
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:1.8.0_171]
	at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:184) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapCanvas.drawImage(CraftMapCanvas.java:65) ~[server.jar:git-Spigot-3d850ec-809c399]
	at fr.moribus.imageonmap.image.Renderer.render(Renderer.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapView.render(CraftMapView.java:146) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.WorldMap.a(WorldMap.java:288) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ItemWorldMap.a(ItemWorldMap.java:305) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:101) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.EntityTracker.updatePlayers(EntityTracker.java:182) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:834) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Xeddius** [comment]
It helps to list the version of linux you're trying to run this on, along with the details of what desktop manager/interface you use.

**Comment by totemo** [comment]
As I discussed in #56 [here](https://github.com/zDevelopers/ImageOnMap/issues/56#issuecomment-596056848) this seems to be a consequence of having `$DISPLAY` set to something.

You can try adding `-Djava.awt.headless=true` _*before*_ the server JAR file name. Or simply unset that environment variable in the shell with `unset DISPLAY`.

The ideal resolution would be to add a note about this in the documentation, since UNIX neophytes running Minecraft servers on UNIX-like systems is probably quite a common scenario.
