### ISSUE TITLE
1.13.x support

### ISSUE THREAD

**Issue by Nicofisi** [zDevelopers/ImageOnMap#55]
That's it. 1.13.x support

```
[01:58:09 INFO]: Nicofisi użył komendy /tomap http://static.cdprojektred.com/thewitcher.com/media/wallpapers/witcher3/full/witcher3_en_wallpaper_the_witcher_3_wild_hunt_ciri_meditating_1920x1080_1446715311.png
[01:58:11 WARN]: [ImageOnMap] Task #22 for ImageOnMap v3.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(I)V
        at fr.moribus.imageonmap.tools.items.GlowEffect.<init>(GlowEffect.java:53) ~[?:?]
        at fr.moribus.imageonmap.tools.items.GlowEffect.getGlow(GlowEffect.java:83) ~[?:?]
        at fr.moribus.imageonmap.tools.items.GlowEffect.addGlow(GlowEffect.java:107) ~[?:?]
        at fr.moribus.imageonmap.tools.items.ItemStackBuilder.item(ItemStackBuilder.java:185) ~[?:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.makeSplatterMap(SplatterMapManager.java:60) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.give(MapItemManager.java:78) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.give(MapItemManager.java:64) ~[?:?]
        at fr.moribus.imageonmap.map.ImageMap.give(ImageMap.java:84) ~[?:?]
        at fr.moribus.imageonmap.commands.maptool.NewCommand$1.finished(NewCommand.java:70) ~[?:?]
        at fr.moribus.imageonmap.commands.maptool.NewCommand$1.finished(NewCommand.java:65) ~[?:?]
        at fr.moribus.imageonmap.components.worker.WorkerCallbackManager$WorkerRunnableInfo.runCallback(WorkerCallbackManager.java:141) ~[?:?]
        at fr.moribus.imageonmap.components.worker.WorkerCallbackManager.run(WorkerCallbackManager.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-193]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-193]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1000) ~[patched_1.13.1.jar:git-Paper-193]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-193]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-193]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-193]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by klugemonkey** [comment]
zLib needs updating since EnchantmentWrapper no longer takes id, but rather a string.  zLib probably should be fixed for 1.13, since other issues with Banner colors need to be addressed.

**Comment by tianji1993** [comment]
this maybe helpful:
https://www.spigotmc.org/threads/enchantmentwrapper-constructor-arguments-changing-with-versions.329593/

**Comment by Xeddius** [comment]
I too would like to see this updated for 1.13.x It has been an essential part of my server for years and before this I used ImageToMap, etc. 1.13 broke this awesome plugin and I really hope it can be fixed soon.

**Comment by AmauryCarrade** [comment]
You have to understand that I have to make choices and priorities. IoM is _not_ abandoned, but there is a whole chain of dependencies to update before and it is a certain work, plus other unrelated and higher-priority projects.

I hope to be able to update IoM before 2019.

**Comment by Tiplish** [comment]
Hi,

I would know if the plugin will manage 1.13.X support before summer? I've some features which work with IoM and i have to know if i could wait or choose another way than this plugin to fit my needs :s 

Thanks for the answer.

**Comment by AmauryCarrade** [comment]
I have been waiting a long time, for both independent and personal reasons, but I am committed to migrating the plugin by this summer, and I hope before that. I'll work on it as my next personal project, after finishing a current one with a close deadline :) .

**Comment by Tiplish** [comment]
Thanks, i will commit that to my team, thanks ;)

**Comment by Xernium** [comment]
@Nicofisi @klugemonkey @tianji1993 @Xeddius @AmauryCarrade     
I just completed updating the plugin to 1.13.2 Ill be uploading the source code in a few min :D

**Comment by Xernium** [comment]
https://github.com/zDevelopers/ImageOnMap/pull/58 @Nicofisi @klugemonkey @tianji1993 @Xeddius @AmauryCarrade has one known gotcha. Other than that works :)

**Comment by Nicofisi** [comment]
Great, thank you! Will try with friends later this week

**Comment by Tiplish** [comment]
Have you the jar somewhere?

**Comment by Tiplish** [comment]
i've try your version @Xernium  but... it doesn't work :( Even if i change the POM to specify 1.13.2.

**Comment by Xernium** [comment]
@Tiplish Woah there! If you’re having issues shoot me a DM on Twitter @Xernium or message me on Discord at `LDX 0xFF, R17;#3114`

**Comment by Tiplish** [comment]
I'm not sure to know how to contact you by discord (impossible to add you as friend :p)

**Comment by Xernium** [comment]
@Tiplish I do have my friends settings set to open. I can try adding you instead if you don't mind sharing your nametag#number

**Comment by Tiplish** [comment]
Tiplish#8686 :)

**Comment by AmauryCarrade** [comment]
4.0-pre1 (including 1.13 and 1.14 support) [has been released](https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.0-pre.1)!
