### ISSUE TITLE
Problem with using ImageOnMap on a 1.15 Server

### ISSUE THREAD

**Issue by snowy6409** [zDevelopers/ImageOnMap#63]
Hello, I have just updated my server to 1.15 and found that there appears to be a problem with the /tomap command running. When ever I try to run the command to a valid link it throws an error in the console about achievements.

`[20:56:07] [Server thread/WARN]: [ImageOnMap] Task #25 for ImageOnMap v4.0-pre1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/Achievement
	at fr.moribus.imageonmap.tools.items.ItemStackBuilder.title(ItemStackBuilder.java:368) ~[?:?]
	at fr.moribus.imageonmap.ui.SplatterMapManager.makeSplatterMap(SplatterMapManager.java:52) ~[?:?]
	at fr.moribus.imageonmap.ui.MapItemManager.give(MapItemManager.java:79) ~[?:?]
	at fr.moribus.imageonmap.ui.MapItemManager.give(MapItemManager.java:65) ~[?:?]
	at fr.moribus.imageonmap.map.ImageMap.give(ImageMap.java:84) ~[?:?]
	at fr.moribus.imageonmap.commands.maptool.NewCommand$1.finished(NewCommand.java:88) ~[?:?]
	at fr.moribus.imageonmap.commands.maptool.NewCommand$1.finished(NewCommand.java:81) ~[?:?]
	at fr.moribus.imageonmap.components.worker.WorkerCallbackManager$WorkerRunnableInfo.runCallback(WorkerCallbackManager.java:141) ~[?:?]
	at fr.moribus.imageonmap.components.worker.WorkerCallbackManager.run(WorkerCallbackManager.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Achievement
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 16 more`

**Comment by AmauryCarrade** [comment]
Okay, it looks like this is a zLib issue instead of a ImageOnMap one. Legacy achievements were removed from 1.15. I'll fix that when possible!
