### ISSUE TITLE
Error happened when placing a poster on the floor.

### ISSUE THREAD

**Issue by developer-ken** [zDevelopers/ImageOnMap#84]
Error happened when placing a poster on the floor.
The following information might be helpful.
`[20:06:53 ERROR]: Could not pass event PlayerInteractEntityEvent to ImageOnMap v4.0-pre2
java.lang.IllegalArgumentException: Only N/S/E/W orientations are supported
        at fr.moribus.imageonmap.tools.world.FlatLocation.<init>(FlatLocation.java:75) ~[?:?]
        at fr.moribus.imageonmap.tools.world.FlatLocation.<init>(FlatLocation.java:111) ~[?:?]
        at fr.moribus.imageonmap.ui.SplatterMapManager.placeSplatterMap(SplatterMapManager.java:172) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onItemFramePlace(MapItemManager.java:236) ~[?:?]
        at fr.moribus.imageonmap.ui.MapItemManager.onEntityInteract(MapItemManager.java:301) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.15.2.jar:git-Paper-245]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2031) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by Vlammar** [comment]
Not implemented on the current version, I'm still trying to finalize the 4.0 release. You will be able to put on floor or ceilling map
