### ISSUE TITLE
Error in console, when /tomap url

### ISSUE THREAD

**Issue by Guest1131** [zDevelopers/ImageOnMap#87]
Hi, I have spigot version 1.13.2, and I installed the IageOnMap 4.0 pre-1 plugin.

But when I load the image with /tomap url, from an error in the console: this :

The map appears in the slot, but the picture does not appear on the map, and this error appears in the console :

java.lang.NoSuchMethodError: org.bukkit.Bukkit.getMap(I)Lorg/bukkit/map/MapView;
        at fr.moribus.imageonmap.image.Renderer.installRenderer(Renderer.java:52) ~[?:?]
        at fr.moribus.imageonmap.image.Renderer.installRenderer(Renderer.java:46) ~[?:?]
        at fr.moribus.imageonmap.image.ImageRendererExecutor$5.call(ImageRendererExecutor.java:131) ~[?:?]
        at fr.moribus.imageonmap.image.ImageRendererExecutor$5.call(ImageRendererExecutor.java:127) ~[?:?]
        at fr.moribus.imageonmap.components.worker.WorkerMainThreadExecutor$WorkerFuture.runCallable(WorkerMainThreadExecutor.java:108) ~[?:?]
        at fr.moribus.imageonmap.components.worker.WorkerMainThreadExecutor.run(WorkerMainThreadExecutor.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[08:49:29 ERROR]: Could not pass event PlayerItemHeldEvent to ImageOnMap v4.0-pre1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1408) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f56e2e7-98b862a]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getMap(I)Lorg/bukkit/map/MapView;
        at fr.moribus.imageonmap.image.MapInitEvent.initMap(MapInitEvent.java:111) ~[?:?]
        at fr.moribus.imageonmap.image.MapInitEvent.initMap(MapInitEvent.java:105) ~[?:?]
        at fr.moribus.imageonmap.image.MapInitEvent.onPlayerInv(MapInitEvent.java:78) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-f56e2e7-98b862a]
        ... 15 more

**Comment by Vlammar** [comment]
Hello, sorry for not responding to you previously, your bug is caused by a missing method, this is an error caused by reflexion, we used to use a lot of reflexion for compatibility issues (that's why we dropped older version btw). I will take a look tonight if I can fix it. @AmauryCarrade
